//  export const articles = [
//   //  { id: 1, genre:[0,1], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"ambush.mp4" },
//   //  { id: 3, genre:[0,1], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"redbull.mp4" },
//    { id: 4, genre:[0,2], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/hilumia.webp" },
//    { id: 5, genre:[0,6], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/nyc_party.webp" },
//   //  { id: 2, genre:[0,2], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-8 row-span-4 overflow-hidden",thumbnail:"/elementals.mp4" },
//    { id: 6, genre:[0,5], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/hilumia.webp" },
//   //  { id: 10, genre:[0,5], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-8 row-span-4 overflow-hidden",thumbnail:"/elementals.mp4" },
//    { id: 8, genre:[0,5], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/hilumia.webp" },
//   //  { id: 9, genre:[0,3], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-8 row-span-4 overflow-hidden",thumbnail:"/elementals.mp4" },
//     { id: 11, genre:[0,1], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/nyc_party.webp" },
//     // { id: 7, genre:[0,4], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"redbull.mp4" },
//     { id: 12, genre:[0,6], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/hilumia.webp" },
//     // { id: 13, genre:[0,2], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-8 row-span-4 overflow-hidden",thumbnail:"/elementals.mp4" },
//     { id: 14, genre:[0,6], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/hilumia.webp" },
//     // { id: 15, genre:[0,1], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"ambush.mp4" },
//     // { id: 16, genre:[0,1], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"redbull.mp4" },
//     { id: 17, genre:[0,2], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/nyc_party.webp" },
//     { id: 18, genre:[0,6], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/hilumia.webp" },
//     // { id: 19, genre:[0,2], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-8 row-span-4 overflow-hidden",thumbnail:"/elementals.mp4" },
//     { id: 20, genre:[0,5], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/hilumia.webp" },
//     // { id: 21, genre:[0,5], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-8 row-span-4 overflow-hidden",thumbnail:"/elementals.mp4" },
//     { id: 22, genre:[0,5], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/nyc_party.webp" },
//     // { id: 23, genre:[0,3], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-8 row-span-4 overflow-hidden",thumbnail:"/elementals.mp4" },
//      { id: 24, genre:[0,1], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/hilumia.webp" },
//     //  { id: 25, genre:[0,4], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"redbull.mp4" },
//      { id: 26, genre:[0,6], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/hilumia.webp" },
//     //  { id: 27, genre:[0,2], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-8 row-span-4 overflow-hidden",thumbnail:"/elementals.mp4" },
//      { id: 28, genre:[0,6], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/nyc_party.webp" },
//     //  { id: 29, genre:[0,1], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"ambush.mp4" },
//   //  { id: 30, genre:[0,1], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"redbull.mp4" },
//    { id: 31, genre:[0,2], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/hilumia.webp" },
//    { id: 32, genre:[0,6], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/nyc_party.webp" },
//   //  { id: 33, genre:[0,2], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-8 row-span-4 overflow-hidden",thumbnail:"/elementals.mp4" },
//    { id: 34, genre:[0,5], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/hilumia.webp" },
//   //  { id: 35, genre:[0,5], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-8 row-span-4 overflow-hidden",thumbnail:"/elementals.mp4" },
//    { id: 36, genre:[0,5], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/nyc_party.webp" },
//   //  { id: 37, genre:[0,3], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-8 row-span-4 overflow-hidden",thumbnail:"/elementals.mp4" },
//     { id: 38, genre:[0,1], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/hilumia.webp" },
//     // { id: 39, genre:[0,4], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"redbull.mp4" },
//     { id: 40, genre:[0,6], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/nyc_party.webp" },
//     // { id: 41, genre:[0,2], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-8 row-span-4 overflow-hidden",thumbnail:"/elementals.mp4" },
//     { id: 42, genre:[0,6], title: "Great times",type:"",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-8 row-span-4 overflow-hidden",thumbnail:"/nyc_party.webp" },
//   ];



 export const articles = [
  //  { id: 1, genre:[0,1], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"ambush.mp4" },
   { id: 1, genre:[0,1], title: "Iphone Landing Page",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-8 row-span-4 overflow-hidden",thumbnail:"/projects/CardPhone.mp4" },
    { id: 6, genre:[0,2], title: "Great times",type:"",  styles:" col-span-4 row-span-4 overflow-hidden",thumbnail:"/hilumia.webp" ,link:"https://www.youtube.com/watch?v=dQw4w9WgXcQ"},
   { id: 2, genre:[0,2], title: "Great times",type:"",  styles:"rounded-xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/hilumia.webp" ,link:"https://www.youtube.com/watch?v=dQw4w9WgXcQ"},
   { id: 3, genre:[0,2], title: "Great times",type:"",  styles:"rounded-xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/hilumia.webp" ,link:"https://www.youtube.com/watch?v=dQw4w9WgXcQ"},
   { id: 4, genre:[0,2], title: "Great times",type:"",  styles:"rounded-xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/hilumia.webp" ,link:"https://www.youtube.com/watch?v=dQw4w9WgXcQ"},
   { id: 5, genre:[0,2], title: "Great times",type:"",  styles:"rounded-xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"/hilumia.webp" ,link:"https://www.youtube.com/watch?v=dQw4w9WgXcQ"},
 ]

 export const particles = [
  //  { id: 1, genre:[0,1], title: "Great times",type:"video",  styles:"rounded-3xl bg-black m-.5 text-white   col-span-4 row-span-4 overflow-hidden",thumbnail:"ambush.mp4" },
  { id: 1, genre:[0,2], title: "YT video content generator",headsup:"IIT Delhi Tryst'24 hackathon winner",type:"",  thumbnail:"/hilumia.webp" ,link:"https://x.com/Fetch_ai/status/1780159291967656036",github:"https://github.com/AleenDhar/Youtube-shorts-creation",description:"Made using Fetch.ai's uagent technology to automatically create Image , Story and an Audio narration of the story. APIs used Google Gemini, ElevenLabs and Cloudinary."},
  { id: 2, genre:[0,2], title: "YTchatbot ",headsup:"Chat with youtube video",type:"",  thumbnail:"/hilumia.webp" ,link:"https://github.com/AleenDhar/chat-with-video",github:"https://github.com/AleenDhar/chat-with-video",description:"It is a Chrome extension made using Gemini API, Next.js, Vercel AI, Pinecone DB, Langcchain, Drizzle. The purpose of this project was to create a chatbot chrome extension that can chat with you about any topic, and it can also chat with you about youtube videos."},
  { id: 3, genre:[0,2], title: "GHOSTAI",headsup:"Collection of multiple AI tools",type:"",  thumbnail:"/hilumia.webp" ,link:"https://ghostsai.vercel.app/tools/games/aicompanion",github:"https://ghostsai.vercel.app/tools/games/aicompanion",description:"Tech Stack: NEXTjs, Clerk(for authentication),Vercel AI, Pinecone, AWS S3, ShadCN"},
  { id: 4, genre:[0,2], title: "Search LLM ",headsup:"Search the web with LLM",type:"",  thumbnail:"/hilumia.webp" ,link:"https://github.com/AleenDhar/llm-web",github:"https://github.com/AleenDhar/llm-web",description:"Integrated SERP API into Lanchain agents, empowering them with real-time web search capabilities. This enhancement enables the agents to emulate System 2 thinking, as depicted in the illustration on the right. "},
  { id: 4, genre:[0,2], title: "Image2Story ",headsup:"Langchain, Huggingface",type:"",  thumbnail:"/hilumia.webp" ,link:"https://www.linkedin.com/posts/aleendhar_generate-a-story-from-just-one-image-activity-7176260705875058688-52CN?utm_source=share&utm_medium=member_desktop",github:"https://github.com/AleenDhar/Ima2story/tree/main",description:"While exploring the possibilities with langchain and huggingface models,I thought of making something that can create stories from just one image"},
  // { id: 4, genre:[0,1], title: "IPHONE LANDING PAGE",headsup:"",type:"video",thumbnail:"/projects/CardPhone.mp4",link:"",github:"https://github.com/AleenDhar/Youtube-shorts-creation",description:"Created a blah blah blah which is blah blah and 100X blah blah Created a blah blah blah which is blah blah and 100X blah blah Created a blah blah blah which is blah blah and 100X blah blah Created a blah blah blah which is blah blah and 100X blah blah"},

 ]